### ISSUE TITLE
Close command

### ISSUE THREAD

**Issue by ghost** [zhon12345/Ticket-Bot#16]
Hello, 
I have used you close command 2 months ago and it worked fine, I got output and all:
![image](https://user-images.githubusercontent.com/89645496/131133378-46ab97f7-6e43-4b94-9c3a-dec4e320e444.png)

But i started my bot again today after those 2 months and I got this error 
![image](https://user-images.githubusercontent.com/89645496/131133257-459434a8-ec3b-48ef-8fad-7c6b75178c96.png)
wich is weird since the last time i used it and i didn't change anything its broken now

Am i just stupid and do i have to update my NPM and if i have to how? Or is there another thing u know about atm?

My code i use is in dutch but don't mind that :)
https://sourceb.in/I5CWV9qN9m

Hopefully you can help me

Kind regards
DarkWarrior

**Comment by zhon12345** [comment]
ok, so the error is coming from line 40 of `close.js`. There it is supposed to dm a member the following "Here is a transcript of your ticket, please click the link below to view the transcript" and an embed. 

You're getting that error probably because the bot is unable to dm the member, most likely they have their dms off. You can fix this by simply adding a `try...catch` function.
